### ISSUE TITLE
bot doesn't start

### ISSUE THREAD

**Issue by CALO77103** [nimiology/telegram_spotify_downloader_bot#1]
wneh I start main.py in python it say this
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    bot.sendMessage(nima,"Now I'm alive")
  File "/home/calo77103/.local/lib/python3.8/site-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/home/calo77103/.local/lib/python3.8/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/calo77103/.local/lib/python3.8/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/home/calo77103/.local/lib/python3.8/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})
is that a bug or my error?

**Comment by nimiology** [comment]
sorry it was my fault 
bug fixed

**Comment by CALO77103** [comment]
Ok fixed but there is another problem should I continue here or create another one?

**Comment by nimiology** [comment]
I think it's better if you create another one.
